In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# ======== 파라미터 ========
training_steps = 22000
display_step = 1000

In [3]:
# ======== 학습데이터 ========
xy = np.loadtxt('train.txt', unpack=True, dtype='float32')

# 학습시간, 해외거주
x_data = xy[0:-1]

# 토익점수
y_data = xy[-1]

#  배열 위치 변환
X = x_data[:].T
print(X)
Y = y_data.reshape(-1,1)
print(Y)

[[54. 12.]
 [ 8.  0.]
 [30. 12.]
 [24. 15.]
 [46. 12.]
 [12.  0.]
 [20. 36.]
 [37. 12.]
 [40. 12.]
 [48. 24.]]
[[800.]
 [320.]
 [600.]
 [630.]
 [700.]
 [300.]
 [920.]
 [720.]
 [700.]
 [920.]]


In [4]:
# ======== W, B 초기값 설정 =========
W = tf.Variable(tf.random.normal((2,1)))
b = tf.Variable(np.random.randn(), name="bias")
W[0]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.03992168], dtype=float32)>

In [5]:
# ======== Multiple Linear Regression 에서 학습될 가설 ========
# Linear regression (Wx + b).
def linear_regression(X):
    return tf.matmul(X, W) + b

In [6]:
# ======== Multiple Linear Regression 에서 학습될 가설의 Cost Function ========
# Mean square error.
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true)) 

In [7]:
# ======== Gradient Descent Algorithm 에서 Step ========
learning_rate = 0.0006

In [8]:
# ======== 텐서플로우에 내장된 GradientDescentOptimizer ========
# Stochastic Gradient Descent Optimizer.
optimizer = tf.optimizers.SGD(learning_rate)

In [9]:
# ======== GradientDescentOptimizer ========
# Optimization process. 
def run_optimization():
    # Wrap computation inside a GradientTape for automatic differentiation. : 자동 미분
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)

    # Compute gradients.
    # gradients = g.gradient(cost, [W, b])
    
    # Update W and b following gradients.
    # optimizer.apply_gradients(zip(gradients, [W, b]))
    
    weight, bias = g.gradient(cost, [W, b])
    W.assign_sub(learning_rate * weight)
    b.assign_sub(learning_rate * bias)

In [10]:
# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % display_step == 0:
        pred = linear_regression(X)
        cost = mean_square(pred, Y)
        print("step: %i, cost: %f, W1: %f, W2: %f, b: %f" % (step, cost, W[0].numpy(), W[1].numpy(), b.numpy()))
        #print("예측값 : {}".format(pred.numpy()))
        
        '''
        print("cost type: {}".format(type(cost)))
        print("W type: {}".format(type(W)))
        print("b type: {}".format(type(b)))
        print("pred type: {}".format(type(pred)))
        '''

step: 1000, cost: 7062.544434, W1: 10.898037, W2: 17.661491, b: 42.568439
step: 2000, cost: 4976.122559, W1: 10.167201, W2: 17.192175, b: 77.886459
step: 3000, cost: 3556.757080, W1: 9.564409, W2: 16.805086, b: 107.016617
step: 4000, cost: 2591.179443, W1: 9.067231, W2: 16.485815, b: 131.043015
step: 5000, cost: 1934.310547, W1: 8.657160, W2: 16.222486, b: 150.859863
step: 6000, cost: 1487.450439, W1: 8.318936, W2: 16.005285, b: 167.204727
step: 7000, cost: 1183.457764, W1: 8.039972, W2: 15.826147, b: 180.685883
step: 8000, cost: 976.654175, W1: 7.809880, W2: 15.678390, b: 191.805145
step: 9000, cost: 835.969910, W1: 7.620106, W2: 15.556524, b: 200.976120
step: 10000, cost: 740.263611, W1: 7.463577, W2: 15.456006, b: 208.540405
step: 11000, cost: 675.155884, W1: 7.334475, W2: 15.373103, b: 214.779343
step: 12000, cost: 630.864624, W1: 7.227993, W2: 15.304724, b: 219.925140
step: 13000, cost: 600.732117, W1: 7.140166, W2: 15.248325, b: 224.169403
step: 14000, cost: 580.234741, W1: 7.067

In [11]:
# ======== 학습된 우리의 프로그램에 예측 문의 ========

sample = np.array([
    [30, 10] 
], dtype=np.float32)

sample1 = np.array([
    [2, 24] 
], dtype=np.float32)

# 30 시간 공부하고 10개월 해외에서 거주했을 경우 토익점수 예측
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample[0,0], sample[0,1], linear_regression(sample).numpy()))
print ("%i 시간, %i 개월 해외거주: %f 점" % (sample1[0,0], sample1[0,1], linear_regression(sample1).numpy()))

30 시간, 10 개월 해외거주: 594.909973 점
2 시간, 24 개월 해외거주: 614.933105 점
